### ISSUE TITLE
Utility Viewer - Valve Status Tracker - Valve Access

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/102_Utility_Viewer#14]
Currently, valve access is tracking access issues, but we have no way to indicate that the issue has been resolved / removed.

Please add the following to the dropdown:
Roadway Vault
Valve Vault

![image](https://cloud.githubusercontent.com/assets/7118831/5619379/36a8d1bc-94ef-11e4-81e9-42ceabe2fee3.png)

**Comment by jday3** [comment]
I added those dropdown values on dev. Adding an access date will require updating the schema/feature service

**Comment by alanfoster99** [comment]
Well, we don't want to do this after all -- please remove from dev.  Sorry for the effort.

**Comment by jday3** [comment]
no problem, it only took a few minutes

**Comment by alanfoster99** [comment]
Thanks!
