### ISSUE TITLE
Utility Viewer - Discrepancy - Source

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/102_Utility_Viewer#15]
When listing a path for the source of the discrepancy, the progress bar continuously updates and the point does not submit.

![image](https://cloud.githubusercontent.com/assets/7118831/5647981/b703db8a-9658-11e4-88de-5a1b3cac626d.png)

**Comment by jday3** [comment]
Is this in production?

**Comment by jday3** [comment]
It could be related to [this issue](https://github.com/JMurk/Utility_Viewer_Issues/issues/141)

**Comment by JMurk** [comment]
Yes, that field is only 50 characters.  Should we make it larger?

**Comment by alanfoster99** [comment]
I vote yes

**Comment by JMurk** [comment]
I updated the size to 255 on dev.  I'm closing this issue and will track it on the one Jesse linked above.
