### ISSUE TITLE
Utility Viewer - Scroll Bar on Identify Results 

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/102_Utility_Viewer#16]
When selecting a large amount of items for identification, the scroll bar does not properly size for the results, and the scroll wheel must be used to access all values.  This is visible in IE.

![image](https://cloud.githubusercontent.com/assets/7118831/8549815/d966a57e-249a-11e5-8521-cb91714f5a53.png)

**Comment by JMurk** [comment]
See https://github.com/JMurk/Utility_Viewer_Issues/issues/180
